export const DISABLE_ACTION_BTN = "DISABLE_ACTION_BTN";
export const ENABLE_ACTION_BTN = "ENABLE_ACTION_BTN";
export const INIT_LOADER = "INIT_LOADER";
export const DISMISS_LOADER = "DISMISS_LOADER";
